spring.application.name=demo

# Base de datos Mongo
spring.data.mongodb.database=task_tracker
spring.mongodb.embedded.version=false
spring.data.mongodb.uri=${mongo_url}
spring.data.mongodb.repositories.enabled=true

spring.data.mongodb.auto-index-creation=true

# Puerto Render
server.port=${PORT:8080}

# Configuración básica de Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=task_tracker.demo.controller

# Forzar a Spring Boot a mostrar los detalles del Error 500 en la respuesta HTTP
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never