spring.application.name=demo

# Base de datos Mongo
spring.data.mongodb.database=task_tracker
spring.mongodb.embedded.version=false
spring.data.mongodb.uri=${mongo_url}
spring.data.mongodb.repositories.enabled=true

# Puerto Render
server.port=${PORT:8080}

# Configuración básica de Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=task_tracker.demo.controller