spring.application.name=demo

# Variante moderna para Spring Boot 3.x
spring.data.mongodb.database=task_tracker
spring.mongodb.embedded.version=false
spring.data.mongodb.uri=${mongo_url}
spring.data.mongodb.repositories.enabled=true

# Puerto para Render
server.port=${PORT:8080}

# Cabeceras Proxy corporativas
server.forward-headers-strategy=framework

# CONFIGURACIÓN SWAGGER LIMPIA Y RELATIVA
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=task_tracker.demo.controller
springdoc.swagger-ui.configUrl=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs